-- MySQL Script generated by MySQL Workbench
-- Fri Oct  2 12:07:06 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FACILoad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FACILoad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FACILoad` DEFAULT CHARACTER SET utf8 ;
USE `FACILoad` ;

-- -----------------------------------------------------
-- Table `FACILoad`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FACILoad`.`users` (
  `id` INT(100) NOT NULL AUTO_INCREMENT,
  `login_id` INT(32) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `hash_password` VARCHAR(100) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `department` VARCHAR(45) NOT NULL,
  `college` VARCHAR(45) NOT NULL,
  `academic_rank` VARCHAR(45) NOT NULL,
  `total_lab_units` INT NOT NULL,
  `total_lec_units` INT NOT NULL,
  `total_extra_units` INT NOT NULL,
  `login_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `logout_at` DATETIME NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `FACILoad`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FACILoad`.`subjects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sub_code` INT NOT NULL,
  `sub_name` VARCHAR(45) NOT NULL,
  `sub_program` VARCHAR(45) NOT NULL,
  `sub_year` VARCHAR(45) NOT NULL,
  `sub_sem` VARCHAR(45) NOT NULL,
  `sub_lab_hours` INT NOT NULL,
  `sub_lec_hours` INT NOT NULL,
  `sub_total_hours` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FACILoad`.`sections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FACILoad`.`sections` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sec_code` VARCHAR(45) NOT NULL,
  `sec_name` VARCHAR(45) NOT NULL,
  `sec_prog` VARCHAR(45) NOT NULL,
  `sec_size` INT NOT NULL,
  `sec_year` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FACILoad`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FACILoad`.`rooms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `room_code` VARCHAR(45) NOT NULL,
  `room_name` VARCHAR(45) NOT NULL,
  `room_time` VARCHAR(45) NOT NULL,
  `room_type` VARCHAR(45) NOT NULL,
  `room_size` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FACILoad`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FACILoad`.`sessions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `faculty_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  `section_id` INT NOT NULL,
  `room_id` INT NOT NULL,
  `ses_type` VARCHAR(45) NOT NULL,
  `ses_units` INT NOT NULL,
  `ses_day` VARCHAR(45) NOT NULL,
  `ses_start` TIME NOT NULL,
  `ses_end` TIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `faculty_id_idx` (`faculty_id` ASC) VISIBLE,
  INDEX `room_id_idx` (`room_id` ASC) VISIBLE,
  INDEX `section_id_idx` (`section_id` ASC) VISIBLE,
  INDEX `subject_id_idx` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `faculty_id`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `FACILoad`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `room_id`
    FOREIGN KEY (`room_id`)
    REFERENCES `FACILoad`.`rooms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `section_id`
    FOREIGN KEY (`section_id`)
    REFERENCES `FACILoad`.`sections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `subject_id`
    FOREIGN KEY (`subject_id`)
    REFERENCES `FACILoad`.`subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
